# tui.py: SessionLocao
# provides the ui and configures app.
import os

import questionary as q
from questionary import Choice
from sqlalchemy import select
from sqlalchemy.orm import Session

from src.ai_core import generate_log_desc, generate_solution
from src.config import load_config, save_config
from src.database import Incident, SessionLocal


def view_resolved_log(log: Incident):
    clear_screen()
    print(f"========== Solved incident ID {log.id} ==========\n")
    print(f"Original issue: {log.raw_log.strip()}")
    print("========== Script that helped ==========")
    print(log.ai_summary.strip() if log.ai_summary else "Script is not available.")
    print("\n===================================================")
    input("Press Enter to return...")


def clear_screen():
    os.system("clear" if os.name == "posix" else "cls")


def ask_for_feedback():
    action = q.select(
        "Did the script execute successfully?",
        choices=[
            Choice("Yes, issue is fixed", value="success"),
            Choice("No, I got an error", value="error"),
            Choice("Abort and exit", value="abort"),
        ],
    ).ask()

    error_output = None
    if action == "error":
        error_output = q.text("Paste the error output from the terminal:").ask()

    return action, error_output


def fix_log(log: Incident, config: dict, db: Session):
    original_status = log.status
    log.status = "processing"
    db.commit()

    previous_error = None

    while True:
        clear_screen()
        print(f"\n[*] Analyzing log ID {log.id} (Attempt {log.attempt})...\n")

        try:
            explanation = "No description"

            if log.executed:
                clean_commands = log.ai_summary
                print("========== [Awaiting Feedback from Previous Run] ==========")
                print(clean_commands)
                print("===========================================================\n")
                print(
                    "Script had already been executed earlier. Type in the result, please."
                )

                action, err_text = ask_for_feedback()

                if action == "success":
                    log.status = "resolved"
                    log.executed = False
                    db.commit()
                    print("\nIncident resolved successfully.")
                    break
                elif action == "error":
                    if err_text:
                        if previous_error:
                            previous_error += f"\n\n[FURTHER ERROR]\n{err_text}"
                        else:
                            previous_error = err_text

                    log.attempt += 1
                    log.executed = False
                    db.commit()
                    continue
                else:  # abort
                    log.status = "waiting"
                    db.commit()
                    print("\nAborted. Task returned to waiting status.")
                    break

            elif (
                original_status == "waiting" and log.attempt == 1 and not previous_error
            ):
                clean_commands = log.ai_summary
                explanation = getattr(log, "ai_log_review", "Auto-generated by Daemon")
                print("========== [Auto-generated by Daemon in background] ==========")

            else:
                explanation, clean_commands = generate_solution(
                    log.raw_log, config, previous_error
                )
                print("========== [Generated Bash Script] ==========")

            if not clean_commands or clean_commands == "MANUAL_INTERVENTION_REQUIRED":
                print(f"[-] AI could not generate a script. Reason: {explanation}")
                log.status = (
                    original_status if original_status != "processing" else "pending"
                )
                db.commit()
                break

            print(f"💡 [AI Analysis]: {explanation}\n")
            print(clean_commands)
            print("=============================================\n")

            script_dir = "data/scripts"
            os.makedirs(script_dir, exist_ok=True)
            script_path = os.path.join(script_dir, f"fix_incident_{log.id}.sh")

            with open(script_path, "w", encoding="utf-8") as f:
                if not clean_commands.startswith("#!"):
                    f.write("#!/bin/bash\n\n")
                f.write(clean_commands)
                f.write("\n")

            os.chmod(script_path, 0o755)
            print(f"[+] Script saved successfully: {script_path}")

            if q.confirm("Run it?").ask():
                log.executed = True
                log.ai_summary = clean_commands
                db.commit()

                os.system(f"./{script_path}")

                action, err_text = ask_for_feedback()

                if action == "success":
                    log.status = "resolved"
                    log.executed = False
                    db.commit()
                    print("\nIncident resolved successfully.")
                    break
                elif action == "error":
                    if err_text:
                        if previous_error:
                            previous_error += f"\n\n[FURTHER ERROR]\n{err_text}"
                        else:
                            previous_error = err_text

                    log.attempt += 1
                    log.executed = False
                    db.commit()
                    continue
                else:
                    print(
                        "\nTask saved in waiting status. You can provide feedback later."
                    )
                    break
            else:
                print(f"You can execute it manually via: ./{script_path}\n")
                log.status = "waiting"
                log.ai_summary = clean_commands
                db.commit()
                input("Press enter to return to the main menu.")
                break

        except Exception as e:
            print(f"[-] App error: {e}")
            log.status = original_status
            db.commit()
            break

    input("Press Enter to return to menu...")


def fix_menu():
    db = SessionLocal()

    try:
        while True:
            clear_screen()
            log_status = q.select(
                "========== Choose the log status ==========",
                [
                    Choice("1. Pending", value="pending"),
                    Choice("2. Waiting", value="waiting"),
                    Choice("3. Solved", value="resolved"),
                    Choice("<- Back", value="back"),
                ],
            ).ask()

            if not log_status or log_status == "back":
                return

            requested_logs = db.scalars(
                select(Incident).where(Incident.status == log_status)
            ).all()

            if not requested_logs:
                print(f"\nNo {log_status} incidents found.")
                input("Press Enter to return...")
                return

            ui_choices = []
            for log in requested_logs:
                desc = getattr(log, "ai_log_review")

                explanation = str("\n" + desc) if desc and desc != "No desc" else ""

                # TODO: implement decent log shorten function
                ui_choices.append(
                    Choice(
                        f"ID {log.id} | {log.raw_log.replace('\n', ' ')[40:110]}"
                        + explanation,
                        value=log,
                    )
                )

            ui_choices += [Choice("<- Back", value="back")]

            selected_log = q.select(
                f"========== Select log to work with ({log_status}) ==========",
                ui_choices,
            ).ask()

            if not selected_log or selected_log == "back":
                return

            if log_status in ["pending", "waiting"]:
                config = load_config()
                fix_log(selected_log, config, db)
            elif log_status == "resolved":
                view_resolved_log(selected_log)

    finally:
        db.close()


def configure_menu(config):
    while True:
        os.system("clear" if os.name == "posix" else "cls")

        aspect = q.select(
            "=========== What you'd like to configure? ==========",
            choices=[
                Choice("1. Mode", value="mode"),
                Choice("2. AI Provider/Model", value="provider"),
                Choice("3. System setup", value="system"),
                Choice("<- Back", value="back"),
            ],
        ).ask()

        if not aspect or aspect == "back":
            return

        match aspect:
            case "mode":
                while True:
                    os.system("clear" if os.name == "posix" else "cls")
                    new_mode = q.select(
                        "========== Select mode ==========",
                        choices=[
                            Choice("1. Manual call", value="manual"),
                            Choice("2. Auto call (choose interval)", value="auto"),
                            Choice("<- Back", value="back"),
                        ],
                    ).ask()

                    if not new_mode or new_mode == "back":
                        break

                    if new_mode == "manual":
                        config["system"]["interval"] = 0
                        save_config(config)
                        print("\nMode changed to Manual.")
                        input("Press Enter to continue...")
                        break
                    elif new_mode == "auto":
                        while True:
                            new_interval = q.text(
                                "Enter an interval in minutes (0 for constant checks): "
                            ).ask()

                            if not new_interval:
                                break

                            if new_interval.isdigit():
                                config["system"]["interval"] = int(new_interval)
                                save_config(config)
                                print(f"\nInterval changed to {new_interval} minutes.")
                                input("Press Enter to continue...")
                                break
                        break

            case "provider":
                while True:
                    os.system("clear" if os.name == "posix" else "cls")
                    providers = list(map(Choice, config["providers"].keys())) + [
                        Choice("New provider (Manual enter)", value="new"),
                        Choice("<- Back", value="back"),
                    ]

                    new_provider = q.select(
                        "========== Select provider ==========", choices=providers
                    ).ask()

                    if not new_provider or new_provider == "back":
                        break

                    if new_provider == "new":
                        provider = q.text("Enter provider name: ").ask()
                        if not provider:
                            continue

                        base_url = q.text("Enter base URL: ").ask()
                        if not base_url:
                            continue

                        api_key = q.text("Enter API key: ").ask()
                        if not api_key:
                            continue

                        config["providers"][provider] = {
                            "base_url": base_url,
                            "api_key": api_key,
                            "model": "",
                            "available_models": [],
                        }
                    else:
                        provider = new_provider
                        if config["providers"][provider]["api_key"] == "":
                            api_key = q.text(
                                f"API key not found. Enter API key for {provider}:"
                            ).ask()
                            if api_key:
                                config["providers"][provider]["api_key"] = api_key
                                os.system("clear" if os.name == "posix" else "cls")
                                input("API key saved.")
                            else:
                                os.system("clear" if os.name == "posix" else "cls")
                                input("API key is empty.")
                                continue

                    config["ai_provider"] = provider

                    os.system("clear" if os.name == "posix" else "cls")
                    models = list(
                        map(
                            Choice,
                            config["providers"][provider].get("available_models", []),
                        )
                    ) + [
                        Choice("New model (Manual enter)", value="new"),
                        Choice("<- Back", value="back"),
                    ]

                    new_model = q.select(
                        f"========== Select model for {provider} ==========",
                        choices=models,
                    ).ask()

                    if not new_model or new_model == "back":
                        continue

                    if new_model == "new":
                        model = q.text("Enter exact model name: ").ask()
                        if not model:
                            continue

                        if (
                            model
                            not in config["providers"][provider]["available_models"]
                        ):
                            config["providers"][provider]["available_models"].append(
                                model
                            )
                    else:
                        model = new_model

                    config["providers"][provider]["model"] = model
                    save_config(config)
                    print(f"\nConfiguration saved: {provider} -> {model}")
                    input("Press Enter to continue...")
                    break

            case "system":
                while True:
                    os.system("clear" if os.name == "posix" else "cls")
                    sys_opt = q.select(
                        "========== System Setup ==========",
                        choices=[
                            Choice("1. Max log length", value="max_log"),
                            Choice("<- Back", value="back"),
                        ],
                    ).ask()

                    if not sys_opt or sys_opt == "back":
                        break

                    if sys_opt == "max_log":
                        new_len = q.text("Enter max log length: ").ask()
                        if new_len and new_len.isdigit():
                            config["system"]["max_log_length"] = int(new_len)
                            save_config(config)
                            print(f"\nMax log length changed to {new_len}.")
                            input("Press Enter to continue...")


def main_menu():
    while True:
        clear_screen()

        config = load_config()

        provider = config["ai_provider"]
        model = config["providers"][provider].get("model", "Unknown")

        option = q.select(
            f"=========== AI system fixer | Current model: {model} ==========\n",
            choices=[
                Choice(title="1. Fix issues", value="fix"),
                Choice(title="2. Configure", value="configure"),
                Choice(title="3. Exit", value="exit"),
            ],
        ).ask()

        match option:
            case "fix":
                fix_menu()
            case "configure":
                configure_menu(config)
            case _:
                clear_screen()
                print("Bye")
                break
